# Generated by Django 5.1.3 on 2024-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
